import streamlit as st
from google import genai # Correct import for the new SDK
from google.genai import types # Required for Imagen configuration
from PIL import Image
from io import BytesIO
import time

# --- 1. ACURA CANADA VISUAL ENGINE (CSS) ---
st.set_page_config(page_title="Acura Precision Configurator", layout="wide")

st.markdown("""
    <style>
    .stApp { background-color: #000000; color: #ffffff; }
    h1, h2, h3 { text-transform: uppercase; letter-spacing: 2px; font-weight: 700 !important; }
    .stButton>button { 
        background-color: #E4002B; color: white; border-radius: 0px; border: none; 
        font-weight: bold; width: 100%; height: 3em; transition: 0.3s;
    }
    .stButton>button:hover { background-color: #ffffff; color: #E4002B; }
    .red-line { height: 4px; background-color: #E4002B; margin: 10px 0 30px 0; }
    .garage-panel { background: #111; padding: 20px; border-left: 5px solid #E4002B; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. 2026 ACURA LINEUP DATA ---
ACURA_MODELS = {
    "Integra Type S": {"hp": 320, "torque": 310, "traits": "The Purist. Raw mechanical connection and 6-speed manual.", "colors": ["Apex Blue Pearl", "Tiger Eye Pearl", "Championship White"]},
    "TLX Type S": {"hp": 355, "torque": 354, "traits": "The Executive Athlete. Turbo V6 and SH-AWD® precision.", "colors": ["Urban Gray Pearl", "Performance Red Pearl", "Majestic Black"]},
    "ADX Platinum": {"hp": 190, "torque": 179, "traits": "The Urban Adventurer. Premium tech for active city living.", "colors": ["Urban Gray Pearl", "Double Apex Blue Pearl II"]},
    "ZDX Type S": {"hp": 500, "torque": 544, "traits": "The Future Specialist. Electric torque and elite 2026 tech.", "colors": ["Double Apex Blue Pearl", "Urban Gray Pearl"]}
}

# --- 3. SESSION STATE ---
if "app_state" not in st.session_state: st.session_state.app_state = "CHAT"
if "selected_car" not in st.session_state: st.session_state.selected_car = "Integra Type S"
if "chat_complete" not in st.session_state: st.session_state.chat_complete = False
if "current_image" not in st.session_state: st.session_state.current_image = None

# Initialize AI Clients
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
model = genai.GenerativeModel('gemini-2.5-flash')

# --- NEW: AI IMAGE GENERATION ENGINE ---
def generate_ai_garage_render(car, color):
    # This prompt creates a 3D, 8k automotive render style
    prompt = (f"Professional 3D automotive studio photography of a 2026 {car} in {color} paint. "
              f"Need for Speed aesthetic, cinematic lighting, aggressive Type S body kit, "
              f"detailed Diamond Pentagon grille, 8k resolution, ray-tracing.")
    
    # We use the new client.models.generate_images function
    client = imagen_client.Client(api_key=st.secrets["GEMINI_API_KEY"])
    response = client.models.generate_images(
        model="imagen-3.0-generate-002",
        prompt=prompt,
        config=imagen_client.types.GenerateImagesConfig(number_of_images=1, aspect_ratio="16:9")
    )
    # Convert the generated bytes into a displayable image
    img_bytes = BytesIO(response.generated_images[0].image.image_bytes)
    return Image.open(img_bytes)

# --- 4. PHASE 1: THE AI INTERVIEW ---
if st.session_state.app_state == "CHAT":
    st.image("https://www.acura.ca/Content/AcuraCA/Static/logo/acura_logo_white.png", width=120)
    st.title("Precision Personality Sync")
    st.markdown('<div class="red-line"></div>', unsafe_allow_html=True)
    
    prompt = st.chat_input("Tell me... do you chase the redline or the horizon?")
    
    if prompt:
        with st.spinner("Analyzing Driver DNA..."):
            res = model.generate_content(f"Recommend one car from {list(ACURA_MODELS.keys())} based on '{prompt}'. Use high energy.")
            st.write(f"### Specialist: {res.text}")
            for car in ACURA_MODELS.keys():
                if car in res.text: st.session_state.selected_car = car
            st.session_state.chat_complete = True

    if st.session_state.chat_complete:
        if st.button(f"ENTER GARAGE: {st.session_state.selected_car.upper()}"):
            st.session_state.app_state = "GARAGE"
            st.rerun()

# --- 5. PHASE 2: THE AI VISUALIZER GARAGE ---
else:
    st.title(f"PROJECT: {st.session_state.selected_car.upper()}")
    st.markdown('<div class="red-line"></div>', unsafe_allow_html=True)
    
    col_vis, col_ui = st.columns([2, 1])
    
    with col_ui:
        st.markdown('<div class="garage-panel">', unsafe_allow_html=True)
        st.subheader("🛠️ CUSTOM CONFIG")
        
        colors = ACURA_MODELS[st.session_state.selected_car]["colors"]
        paint = st.pills("PAINT FINISH", colors, default=colors[0])
        
        st.markdown("---")
        st.subheader("PERFORMANCE HUD")
        stats = ACURA_MODELS[st.session_state.selected_car]
        st.metric("POWER", f"{stats['hp']} HP")
        st.metric("TORQUE", f"{stats['torque']} LB-FT")
        
        if st.button("🚀 GENERATE AI 3D RENDER"):
            with st.spinner("Generating hyper-realistic 3D model..."):
                st.session_state.current_image = generate_ai_garage_render(st.session_state.selected_car, paint)

        if st.button("🔥 LOCK IN BUILD"): st.balloons()
        if st.button("← BACK"):
            st.session_state.app_state = "CHAT"
            st.session_state.chat_complete = False
            st.session_state.current_image = None
            st.rerun()
        st.markdown('</div>', unsafe_allow_html=True)

    with col_vis:
        if st.session_state.current_image:
            st.image(st.session_state.current_image, use_container_width=True)
        else:
            st.info("Click 'GENERATE AI 3D RENDER' to view your custom project build.")

